/**
 * Renders every brand asset from the one geometry source (./geometry.mjs):
 *
 *   brand/mark.svg              — app icon / avatar
 *   brand/wordmark.svg          — lockup for light surfaces
 *   brand/wordmark-inverse.svg  — lockup for dark surfaces
 *   brand/og-card.svg           — 1200x630 social card
 *   public/favicon.svg        — the icon the demo actually serves
 *   public/og-image.png       — 1200x630 raster of og-card.svg (og:image)
 *
 * These are committed, so this only needs re-running when the mark changes:
 *
 *   node brand/build.mjs
 *
 * No dependencies on purpose — it writes strings. A generator that needs an
 * install is a generator nobody re-runs, and a stale committed favicon is the
 * failure mode this file exists to prevent.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  ARMS,
  COLORS,
  FONT_STACK,
  FORK,
  STEM,
  STROKE_WIDTH,
  TAGLINE,
  TILE_RADIUS,
  VIEW_BOX,
  WORDMARK,
  WORDMARK_ADVANCE,
  WORDMARK_X,
} from "./geometry.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");

/** The bare mark: tile, stem, and the two arms carrying the two tones. */
function mark({ toneOne, toneTwo, tile, radius = TILE_RADIUS }) {
  return [
    `<rect width="64" height="64" rx="${radius}" fill="${tile}"/>`,
    `<rect x="${STEM.x}" y="${STEM.y}" width="${STEM.width}" height="${STEM.height}" rx="${STEM.radius}" fill="${toneOne}"/>`,
    `<path d="M${FORK.x} ${FORK.y} L${ARMS[0].x} ${ARMS[0].y}" stroke="${toneOne}" stroke-width="${STROKE_WIDTH}" stroke-linecap="round" fill="none"/>`,
    `<path d="M${FORK.x} ${FORK.y} L${ARMS[1].x} ${ARMS[1].y}" stroke="${toneTwo}" stroke-width="${STROKE_WIDTH}" stroke-linecap="round" fill="none"/>`,
  ].join("\n  ");
}

const LABEL = `${WORDMARK.lead}${WORDMARK.trail}`;
/** Derived, not fixed — see WORDMARK_ADVANCE. The tspans sit on the same
 *  line as their <text>: under xml:space="preserve" any newline/indent
 *  inside it renders as leading spaces and shoves the wordmark right. */
const LOCKUP_WIDTH = Math.ceil(WORDMARK_X + LABEL.length * WORDMARK_ADVANCE + 16);

function markSvg({ square = false } = {}) {
  const radius = square ? 0 : TILE_RADIUS;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${VIEW_BOX}" width="64" height="64" role="img" aria-label="${LABEL} mark">
  <title>${LABEL} mark</title>
  <!-- GENERATED by brand/build.mjs from brand/geometry.mjs. Do not hand-edit.
       The two arms carry the two tones, so the mark states the whole brand
       pair at 16px without needing the wordmark beside it. -->
  ${mark({ toneOne: COLORS.toneOne, toneTwo: COLORS.toneTwo, tile: COLORS.tile, radius })}
</svg>
`;
}

/**
 * Lockup = mark + wordmark. The gap is half the mark's height, which is also
 * the clear space the mark keeps on every side.
 */
function wordmarkSvg({ inverse }) {
  const toneOne = inverse ? COLORS.toneOneInverse : COLORS.toneOne;
  const tile = inverse ? COLORS.tileInverse : COLORS.tile;
  const text = inverse ? COLORS.foregroundInverse : COLORS.foreground;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${LOCKUP_WIDTH} 64" width="${LOCKUP_WIDTH}" height="64" role="img" aria-label="${LABEL}">
  <title>${LABEL}</title>
  <!-- GENERATED by brand/build.mjs. The text is set live in Geist SemiBold
       with a system fallback; outline it before export for print or any
       surface that cannot load Geist. -->
  ${mark({ toneOne, toneTwo: COLORS.toneTwo, tile })}
  <text x="${WORDMARK_X}" y="41" font-family="${FONT_STACK}"
        font-size="26" font-weight="600" letter-spacing="-0.5" xml:space="preserve"><tspan fill="${toneOne}">${WORDMARK.lead}</tspan><tspan fill="${text}">${WORDMARK.trail}</tspan></text>
</svg>
`;
}

function ogCardSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630" role="img" aria-label="${LABEL} — ${TAGLINE}">
  <title>${LABEL} — ${TAGLINE}</title>
  <!-- GENERATED by brand/build.mjs. -->
  <defs>
    <radialGradient id="glow" cx="18%" cy="12%" r="85%">
      <stop offset="0%" stop-color="${COLORS.toneOne}" stop-opacity="0.30"/>
      <stop offset="60%" stop-color="${COLORS.toneOne}" stop-opacity="0.04"/>
      <stop offset="100%" stop-color="${COLORS.toneOne}" stop-opacity="0"/>
    </radialGradient>
    <pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse">
      <path d="M40 0 L0 0 0 40" fill="none" stroke="${COLORS.grid}" stroke-width="1"/>
    </pattern>
  </defs>
  <rect width="1200" height="630" fill="${COLORS.tileInverse}"/>
  <rect width="1200" height="630" fill="url(#grid)"/>
  <rect width="1200" height="630" fill="url(#glow)"/>

  <g transform="translate(96 168) scale(1.5)">
    ${mark({ toneOne: COLORS.toneOneInverse, toneTwo: COLORS.toneTwo, tile: COLORS.tile })}
  </g>

  <text x="96" y="352" font-family="${FONT_STACK}"
        font-size="76" font-weight="600" letter-spacing="-2" xml:space="preserve"><tspan fill="${COLORS.toneOneInverse}">${WORDMARK.lead}</tspan><tspan fill="${COLORS.foregroundInverse}">${WORDMARK.trail}</tspan></text>
  <text x="96" y="410" font-family="${FONT_STACK}"
        font-size="28" font-weight="400" fill="${COLORS.foregroundMutedInverse}">${TAGLINE}</text>
</svg>
`;
}

const written = [];
function write(relative, contents) {
  const target = path.join(ROOT, relative);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents);
  written.push(relative);
}

write("brand/mark.svg", markSvg());
write("brand/wordmark.svg", wordmarkSvg({ inverse: false }));
write("brand/wordmark-inverse.svg", wordmarkSvg({ inverse: true }));
write("brand/og-card.svg", ogCardSvg());
write("public/favicon.svg", markSvg());
/* iOS applies its own mask, so the apple-touch source is SQUARE — a
   pre-rounded tile comes out double-rounded. */
write("brand/mark-square.svg", markSvg({ square: true }));

/*
 * Rasters. Next serves app/favicon.ico for browsers that ignore the SVG, and
 * `metadata.icons` promises an apple-touch-icon; both have to come from the
 * same mark or they drift, which is the whole reason this file exists.
 *
 * sharp ships with Next, so this normally runs. If it ever does not resolve
 * the SVGs are still written and only the rasters are skipped — a generator
 * that dies on an optional step is one nobody runs.
 */
let sharp;
try {
  ({ default: sharp } = await import("sharp"));
} catch {
  console.warn("sharp not resolvable — SVGs written, rasters skipped");
}

if (sharp) {
  const rounded = Buffer.from(markSvg());
  const square = Buffer.from(markSvg({ square: true }));

  /** Minimal ICO container around one PNG per size. */
  function ico(pngs, sizes) {
    const header = Buffer.alloc(6);
    header.writeUInt16LE(0, 0);
    header.writeUInt16LE(1, 2);
    header.writeUInt16LE(pngs.length, 4);
    let offset = 6 + pngs.length * 16;
    const entries = pngs.map((png, i) => {
      const entry = Buffer.alloc(16);
      entry.writeUInt8(sizes[i], 0);
      entry.writeUInt8(sizes[i], 1);
      entry.writeUInt16LE(1, 4);
      entry.writeUInt16LE(32, 6);
      entry.writeUInt32LE(png.length, 8);
      entry.writeUInt32LE(offset, 12);
      offset += png.length;
      return entry;
    });
    return Buffer.concat([header, ...entries, ...pngs]);
  }

  const sizes = [16, 32, 48];
  const pngs = [];
  for (const size of sizes) {
    pngs.push(await sharp(rounded, { density: 1600 }).resize(size, size).png().toBuffer());
  }
  write("app/favicon.ico", ico(pngs, sizes));
  write(
    "app/favicon.png",
    await sharp(rounded, { density: 1600 }).resize(180, 180).png().toBuffer(),
  );
  write(
    "public/apple-touch-icon.png",
    await sharp(square, { density: 1600 }).resize(180, 180).png().toBuffer(),
  );
  /* og:image / twitter:image. Rasterised from the same og-card.svg so the
     social card can never show a different mark than the brand files. */
  write(
    "public/og-image.png",
    await sharp(Buffer.from(ogCardSvg()), { density: 72 }).resize(1200, 630).png().toBuffer(),
  );
}

console.log(`Brand assets written — ${written.join(", ")}`);
