/**
 * Showcase configuration.
 *
 * Generated by scripts/env-to-showcase-config.js from .env.local.
 * Do not edit by hand — re-run the script to regenerate.
 */

export const SHOWCASE_BRAND = {
  /** Short / package-style name (e.g. "KUI-react"). */
  short: "KUI-react",
  /** Display / wordmark name shown in UI (e.g. "KUIreact"). */
  name: "KUIreact",
  /** Initial used in the round logo badge. */
  initial: "K",
  /** Short tagline. */
  tagline: "Composable UI System for Real Products",
  /** Long description used for meta tags and the home panel body. */
  description: "KUIreact is a production-ready UI system built with Next.js. A composable design system and storefront-ready component architecture for real-world applications.",
} as const;

export const SHOWCASE_LINKS = {
  siteUrl: "https://next-js-components.kuray.dev",
  github: "https://github.com/kuraykaraaslan/next_js_components",
  author: {
    name: "Kuray Karaaslan",
    url: "https://kuray.dev",
  },
} as const;

type ColorOverrides = {
  primary: string | null;
  primaryHover: string | null;
  primaryActive: string | null;
  primarySubtle: string | null;
  primaryFg: string | null;
  secondary: string | null;
  secondaryHover: string | null;
  secondaryActive: string | null;
  secondarySubtle: string | null;
  secondaryFg: string | null;
  surfaceBase: string | null;
  surfaceRaised: string | null;
  surfaceOverlay: string | null;
  surfaceSunken: string | null;
  border: string | null;
  borderStrong: string | null;
  borderFocus: string | null;
};

export const SHOWCASE_COLORS: { light: ColorOverrides; dark: ColorOverrides } = {
  light: {
    primary: null,
    primaryHover: null,
    primaryActive: null,
    primarySubtle: null,
    primaryFg: null,
    secondary: null,
    secondaryHover: null,
    secondaryActive: null,
    secondarySubtle: null,
    secondaryFg: null,
    surfaceBase: null,
    surfaceRaised: null,
    surfaceOverlay: null,
    surfaceSunken: null,
    border: null,
    borderStrong: null,
    borderFocus: null,
  },
  dark: {
    primary: null,
    primaryHover: null,
    primaryActive: null,
    primarySubtle: null,
    primaryFg: null,
    secondary: null,
    secondaryHover: null,
    secondaryActive: null,
    secondarySubtle: null,
    secondaryFg: null,
    surfaceBase: null,
    surfaceRaised: null,
    surfaceOverlay: null,
    surfaceSunken: null,
    border: null,
    borderStrong: null,
    borderFocus: null,
  },
};

const TOKEN_MAP: Array<[keyof ColorOverrides, string]> = [
  ['primary', '--primary'],
  ['primaryHover', '--primary-hover'],
  ['primaryActive', '--primary-active'],
  ['primarySubtle', '--primary-subtle'],
  ['primaryFg', '--primary-fg'],
  ['secondary', '--secondary'],
  ['secondaryHover', '--secondary-hover'],
  ['secondaryActive', '--secondary-active'],
  ['secondarySubtle', '--secondary-subtle'],
  ['secondaryFg', '--secondary-fg'],
  ['surfaceBase', '--surface-base'],
  ['surfaceRaised', '--surface-raised'],
  ['surfaceOverlay', '--surface-overlay'],
  ['surfaceSunken', '--surface-sunken'],
  ['border', '--border'],
  ['borderStrong', '--border-strong'],
  ['borderFocus', '--border-focus'],
];

function declarations(overrides: ColorOverrides): string {
  return TOKEN_MAP.map(([key, token]) => {
    const v = overrides[key];
    return v ? `  ${token}: ${v};` : null;
  })
    .filter(Boolean)
    .join('\n');
}

/**
 * Returns a CSS string with the active overrides, or an empty string when
 * no overrides are present.
 */
export function buildShowcaseColorCss(): string {
  const light = declarations(SHOWCASE_COLORS.light);
  const dark = declarations(SHOWCASE_COLORS.dark);
  const parts: string[] = [];
  if (light) parts.push(`:root {\n${light}\n}`);
  if (dark) parts.push(`.dark {\n${dark}\n}`);
  return parts.join('\n');
}
