#!/usr/bin/env node
// Generates index.ts barrel exports for every domain in modules/domains/<vertical>/
// and a top-level modules/domains/index.ts that re-exports each vertical as a namespace.
//
// Re-runs are safe: existing index.ts files are overwritten with the regenerated content.
//
// Detection: walks every .tsx file under each domain, parses `export function|class|const`
// + named `export { ... }` lines to find exported identifiers, and emits a single
// `export { A, B } from './path/File'` line per file. Re-exports `types` if types.ts exists.

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const DOMAINS_DIR = join(ROOT, 'modules', 'domains');
const HEADER = '// Generated by scripts/generate-barrels.mjs — do not edit by hand.\n';

function walkTsxFiles(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const s = statSync(p);
    if (s.isDirectory()) out.push(...walkTsxFiles(p));
    else if (s.isFile() && name.endsWith('.tsx')) out.push(p);
  }
  return out;
}

function extractExports(source) {
  const names = new Set();
  // export function Foo / export class Foo / export const Foo / export let Foo
  const declRe = /^\s*export\s+(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)/gm;
  let m;
  while ((m = declRe.exec(source))) names.add(m[1]);
  // export { Foo, Bar as Baz }
  const namedRe = /^\s*export\s*\{([^}]+)\}/gm;
  while ((m = namedRe.exec(source))) {
    for (const part of m[1].split(',')) {
      const cleaned = part.trim();
      if (!cleaned) continue;
      const alias = cleaned.split(/\s+as\s+/).pop().trim();
      if (alias && /^[A-Za-z_$][\w$]*$/.test(alias)) names.add(alias);
    }
  }
  return [...names].sort();
}

function buildDomainBarrel(domainDir) {
  const files = walkTsxFiles(domainDir).sort();
  const lines = [HEADER];
  const hasTypes = existsSync(join(domainDir, 'types.ts'));
  if (hasTypes) lines.push(`export * from './types';`);
  for (const file of files) {
    const rel = './' + relative(domainDir, file).replace(/\.tsx$/, '').replace(/\\/g, '/');
    const source = readFileSync(file, 'utf8');
    const names = extractExports(source);
    if (names.length === 0) continue;
    lines.push(`export { ${names.join(', ')} } from '${rel}';`);
  }
  return lines.join('\n') + '\n';
}

const domains = readdirSync(DOMAINS_DIR)
  .filter((n) => statSync(join(DOMAINS_DIR, n)).isDirectory())
  .sort();

let total = 0;
for (const d of domains) {
  const dir = join(DOMAINS_DIR, d);
  const barrel = buildDomainBarrel(dir);
  writeFileSync(join(dir, 'index.ts'), barrel);
  total++;
  console.log(`  ✓ modules/domains/${d}/index.ts`);
}

// Top-level domain barrel — namespaced re-exports
const topLines = [HEADER];
for (const d of domains) {
  // Convert kebab-case to PascalCase for namespace name
  const ns = d.split('-').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');
  topLines.push(`export * as ${ns} from './${d}';`);
}
writeFileSync(join(DOMAINS_DIR, 'index.ts'), topLines.join('\n') + '\n');
console.log(`  ✓ modules/domains/index.ts (namespaced)`);

console.log(`\nGenerated ${total} domain barrels + 1 top-level barrel.`);
